# Final Project - NBA All star data preparation

## Import libraries

In [1]:
import pandas as pd
import numpy as np

## reading both df, all star and college players

In [2]:
# reading allstar data file from csv

all_star_df = pd.read_csv('all_star_rosters.csv', index_col = 0)
all_star_df.head()

               Name
0       Dwyane Wade
1      LeBron James
2     Allen Iverson
3  Shaquille O'Neal
4      Vince Carter

In [3]:
all_star_df.shape

(113, 1)

In [4]:
# reading college data clean file from csv

college_players = pd.read_csv('college_data.csv', index_col = 0)
college_players.head()

,player_name,school,GP,Min_per,ORtg,usg,eFG,TS_per,FT_per,twoP_per,...,bpm,mp,oreb,dreb,ast,stl,blk,pts,role,drafted
1,DeAndrae Ross,Troy,7,11.5,67.1,16.9,34.5,36.11,0.500,0.364,...,-10.394000,18.8571,0.5714,1.1429,1.4286,0.1429,0.0000,3.2857,Wing G,No
2,Pooh Williams,Utah St.,33,64.5,105.6,18.7,48.1,52.40,0.815,0.394,...,1.125160,26.0000,0.1515,1.4848,2.0909,0.2121,0.0909,8.6667,Combo G,No
11,Dana Smith,Longwood,27,81.8,99.8,27.7,49.9,53.76,0.658,0.483,...,-0.441037,32.7037,2.1481,4.9259,2.4074,0.8148,0.4815,17.5556,Wing F,No
26,Carlos Strong,Boston University,35,76.2,118.1,16.4,58.8,60.93,0.682,0.478,...,6.077490,30.6857,1.3429,3.2286,1.8000,1.6571,0.4000,10.8571,Combo G,No
27,Sherrod Smith,Boston University,29,9.5,60.7,6.9,8.3,14.93,0.300,0.100,...,-4.128490,4.6207,0.1379,0.5862,0.2069,0.1034,0.0345,0.1724,Wing G,No

## get only drafted players from college

In [5]:

drafted_df=college_players.loc[college_players['drafted'] == 'Yes']

In [6]:
drafted_df.head()

,player_name,school,GP,Min_per,ORtg,usg,eFG,TS_per,FT_per,twoP_per,...,bpm,mp,oreb,dreb,ast,stl,blk,pts,role,drafted
48,Charles Jenkins,Hofstra,32,92.4,123.2,28.7,57.7,62.93,0.825,0.555,...,7.09443,37.4062,0.5000,2.7188,4.6875,1.6562,0.6250,22.5000,Scoring PG,Yes
79,Vernon Macklin,Florida,37,59.7,107.5,24.3,59.3,57.77,0.451,0.593,...,3.88301,24.4595,2.2162,3.1622,0.8108,0.3514,0.7027,11.5676,C,Yes
167,Ryan Reid,Florida St.,31,54.8,97.5,18.3,49.1,51.58,0.597,0.491,...,2.50667,22.7097,1.8710,2.0968,1.1290,0.5806,0.5161,6.7742,C,Yes
171,Kyle Singler,Duke,37,86.9,112.3,23.5,49.1,53.64,0.806,0.497,...,5.95265,34.7568,2.3784,4.4595,1.6216,0.9189,0.3243,16.8919,Wing F,Yes
172,Nolan Smith,Duke,37,85.1,114.0,30.8,50.8,56.40,0.813,0.501,...,7.92525,34.0270,1.1892,3.2973,5.1081,1.2162,0.0811,20.6486,Scoring PG,Yes

## feature engineering

### create all star column in college players data drame based on names in allstar data frame

In [7]:
drafted_df['Allstar'] = np.where(drafted_df.player_name.isin(all_star_df.Name), 'Yes', 'No')

/var/folders/gd/t7jqq6zs1zl6b6b62cxdkccw0000gn/T/ipykernel_16982/3165909800.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drafted_df['Allstar'] = np.where(drafted_df.player_name.isin(all_star_df.Name), 'Yes', 'No')

In [8]:
drafted_df.reset_index()

,index,player_name,school,GP,Min_per,ORtg,usg,eFG,TS_per,FT_per,...,mp,oreb,dreb,ast,stl,blk,pts,role,drafted,Allstar
0,48,Charles Jenkins,Hofstra,32,92.4,123.2,28.7,57.7,62.93,0.825,...,37.4062,0.5000,2.7188,4.6875,1.6562,0.6250,22.5000,Scoring PG,Yes,No
1,79,Vernon Macklin,Florida,37,59.7,107.5,24.3,59.3,57.77,0.451,...,24.4595,2.2162,3.1622,0.8108,0.3514,0.7027,11.5676,C,Yes,No
2,167,Ryan Reid,Florida St.,31,54.8,97.5,18.3,49.1,51.58,0.597,...,22.7097,1.8710,2.0968,1.1290,0.5806,0.5161,6.7742,C,Yes,No
3,171,Kyle Singler,Duke,37,86.9,112.3,23.5,49.1,53.64,0.806,...,34.7568,2.3784,4.4595,1.6216,0.9189,0.3243,16.8919,Wing F,Yes,No
4,172,Nolan Smith,Duke,37,85.1,114.0,30.8,50.8,56.40,0.813,...,34.0270,1.1892,3.2973,5.1081,1.2162,0.0811,20.6486,Scoring PG,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,26794,Day'Ron Sharpe,North Carolina,29,47.9,101.9,27.5,51.9,52.09,0.505,...,19.1724,3.3793,4.2069,1.4483,0.7931,0.8966,9.4828,C,Yes,No
568,26798,Isaiah Jackson,Kentucky,25,51.1,108.0,21.3,54.0,58.69,0.700,...,20.6400,2.1200,4.4800,0.7200,0.7600,2.6000,8.4400,C,Yes,No
569,26893,Greg Brown III,Texas,26,48.9,91.7,25.8,49.7,53.48,0.708,...,20.5769,1.1923,4.9615,0.3846,0.5769,1.0000,9.3462,PF/C,Yes,No
570,26941,Keon Johnson,Tennessee,27,62.5,95.2,27.3,47.4,51.71,0.703,...,25.0000,1.0370,2.4444,2.4815,1.1111,0.4074,11.2593,Wing G,Yes,No
571,26979,Brandon Boston Jr.,Kentucky,25,75.9,96.4,21.4,40.7,44.72,0.785,...,30.6800,1.3200,3.1600,1.6400,1.3200,0.1600,11.4800,Wing G,Yes,No

In [9]:
drafted_df['Allstar'].unique()

array(['No', 'Yes'], dtype=object)

In [10]:
# verify number of allstar players match with allstar df
drafted_df['Allstar'].value_counts()

No     541
Yes     31
Name: Allstar, dtype: int64

In [11]:
drafted_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 572 entries, 48 to 26979
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player_name  572 non-null    object
 1   school       572 non-null    object
 2   GP           572 non-null    int64
 3   Min_per      572 non-null    float64
 4   ORtg         572 non-null    float64
 5   usg          572 non-null    float64
 6   eFG          572 non-null    float64
 7   TS_per       572 non-null    float64
 8   FT_per       572 non-null    float64
 9   twoP_per     572 non-null    float64
 10  TP_per       572 non-null    float64
 11  yr           572 non-null    int64
 12  ht           572 non-null    int64
 13  ast/tov      572 non-null    float64
 14  pick         572 non-null    float64
 15  drtg         572 non-null    float64
 16  bpm          572 non-null    float64
 17  mp           572 non-null    float64
 18  oreb         572 non-null    float64
 19  dreb         572 non-null    float64
 20  ast          572 non-null    float64
 21  stl          572 non-null    float64
 22  blk          572 non-null    float64
 23  pts          572 non-null    float64
 24  role         572 non-null    object
 25  drafted      572 non-null    object
 26  Allstar      572 non-null    object
dtypes: float64(19), int64(3), object(5)
memory usage: 125.1+ KB

In [12]:
drafted_df=drafted_df.reset_index(drop=True)

In [13]:
drafted_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player_name  572 non-null    object
 1   school       572 non-null    object
 2   GP           572 non-null    int64
 3   Min_per      572 non-null    float64
 4   ORtg         572 non-null    float64
 5   usg          572 non-null    float64
 6   eFG          572 non-null    float64
 7   TS_per       572 non-null    float64
 8   FT_per       572 non-null    float64
 9   twoP_per     572 non-null    float64
 10  TP_per       572 non-null    float64
 11  yr           572 non-null    int64
 12  ht           572 non-null    int64
 13  ast/tov      572 non-null    float64
 14  pick         572 non-null    float64
 15  drtg         572 non-null    float64
 16  bpm          572 non-null    float64
 17  mp           572 non-null    float64
 18  oreb         572 non-null    float64
 19  dreb         572 non-null    float64
 20  ast          572 non-null    float64
 21  stl          572 non-null    float64
 22  blk          572 non-null    float64
 23  pts          572 non-null    float64
 24  role         572 non-null    object
 25  drafted      572 non-null    object
 26  Allstar      572 non-null    object
dtypes: float64(19), int64(3), object(5)
memory usage: 120.8+ KB

In [14]:
# showing allstar players, non college, overseas players or players drafted before 2008 won't appear
drafted_df.loc[drafted_df['Allstar'] == 'Yes']

,player_name,school,GP,Min_per,ORtg,usg,eFG,TS_per,FT_per,twoP_per,...,mp,oreb,dreb,ast,stl,blk,pts,role,drafted,Allstar
45,Damian Lillard,Weber St.,30,87.2,122.3,32.3,54.5,62.11,0.885,0.504,...,35.3000,0.5333,4.2667,4.1000,1.5000,0.2333,24.3667,Scoring PG,Yes,Yes
52,Nikola Vucevic,USC,34,87.0,115.9,25.1,53.9,57.80,0.755,0.542,...,34.9118,2.8529,7.4412,1.5882,0.5294,1.3824,17.1176,PF/C,Yes,Yes
55,Paul George,Fresno St.,28,72.6,105.6,27.3,51.0,57.22,0.902,0.489,...,33.1786,1.9286,5.2857,3.0714,2.1429,0.8571,16.7143,Wing F,Yes,Yes
57,Gordon Hayward,Butler,37,81.2,113.3,24.4,52.7,60.13,0.829,0.592,...,33.4865,1.9459,6.2973,1.6757,1.0811,0.8108,15.4595,Stretch 4,Yes,Yes
72,Klay Thompson,Washington St.,34,83.0,107.6,31.9,52.5,57.37,0.838,0.466,...,34.6765,0.7353,4.5000,3.7353,1.6471,0.9412,21.5588,Combo G,Yes,Yes
75,Draymond Green,Michigan St.,37,82.8,107.3,28.2,50.4,54.22,0.723,0.473,...,33.2162,2.1351,8.4865,3.8108,1.4595,0.9730,16.2432,Stretch 4,Yes,Yes
77,Kemba Walker,Connecticut,41,92.4,117.8,31.5,47.8,54.30,0.819,0.471,...,37.6341,1.2927,4.1463,4.4878,1.8780,0.1707,23.5366,Scoring PG,Yes,Yes
78,Jimmy Butler,Marquette,37,86.3,122.0,21.2,51.6,58.67,0.783,0.515,...,34.6486,2.4324,3.6486,2.3243,1.4324,0.3514,15.7297,Wing G,Yes,Yes
104,Khris Middleton,Texas A&M,19,44.3,96.0,28.6,45.1,48.32,0.750,0.481,...,29.0526,1.3684,3.7368,2.1579,0.9474,0.2632,13.1579,Wing F,Yes,Yes
105,John Wall,Kentucky,37,83.9,108.7,26.9,50.3,56.18,0.754,0.509,...,34.8108,0.8108,3.4865,6.5135,1.7838,0.5135,16.6486,Pure PG,Yes,Yes
109,Kawhi Leonard,San Diego St.,34,79.6,108.7,27.7,46.3,50.78,0.759,0.472,...,33.0000,3.1765,7.5294,2.5588,1.4706,0.5882,15.5588,PF/C,Yes,Yes
112,DeMarcus Cousins,Kentucky,38,58.2,113.5,30.8,56.0,57.93,0.604,0.565,...,23.5000,4.0526,5.7895,1.0000,0.9737,1.7632,15.1316,C,Yes,Yes
154,Victor Oladipo,Indiana,36,70.4,122.7,22.6,64.8,67.12,0.746,0.644,...,28.3611,2.5833,3.7500,2.0556,2.1667,0.7778,13.6389,Wing G,Yes,Yes
157,Kyrie Irving,Duke,11,20.5,130.5,27.2,61.5,69.70,0.901,0.569,...,27.5455,0.5455,2.8182,4.2727,1.4545,0.5455,17.4545,Scoring PG,Yes,Yes
178,Andre Drummond,Connecticut,34,70.3,100.7,20.8,53.8,50.93,0.295,0.541,...,28.4412,3.3529,4.2059,0.4412,0.8235,2.7059,10.0000,C,Yes,Yes
196,Bradley Beal,Florida,37,84.7,112.3,22.4,52.5,57.45,0.769,0.541,...,34.2432,1.3514,5.3784,2.2432,1.3784,0.8378,14.7568,Wing G,Yes,Yes
202,Anthony Davis,Kentucky,40,80.1,133.8,19.1,62.8,65.41,0.709,0.653,...,32.0250,2.9750,7.4000,1.2500,1.3500,4.6500,14.1750,C,Yes,Yes
265,Julius Randle,Kentucky,40,76.3,111.2,26.2,50.4,56.59,0.706,0.516,...,30.8250,3.5000,6.9250,1.4250,0.5000,0.7750,14.9750,C,Yes,Yes
279,Zach LaVine,UCLA,37,60.7,107.3,19.0,52.4,54.48,0.691,0.494,...,24.4324,0.4865,2.0541,1.7838,0.8919,0.1622,9.4324,Wing G,Yes,Yes
281,Joel Embiid,Kansas,28,45.9,112.0,24.4,62.9,65.50,0.685,0.639,...,23.1071,2.3214,5.7857,1.3571,0.8929,2.5714,11.1786,C,Yes,Yes
295,Domantas Sabonis,Gonzaga,35,79.9,120.0,26.0,61.2,65.09,0.768,0.615,...,32.0571,3.0286,8.8000,1.8000,0.6000,0.8857,17.4857,PF/C,Yes,Yes
311,Karl-Anthony Towns,Kentucky,39,52.3,122.7,24.2,57.0,62.72,0.813,0.577,...,21.1282,2.3590,4.3333,1.1282,0.4615,2.2564,10.2821,C,Yes,Yes
323,Pascal Siakam,New Mexico St.,32,87.0,115.4,28.0,54.0,56.88,0.686,0.547,...,35.3438,4.0000,7.8438,1.5938,1.0000,2.2188,20.3750,C,Yes,Yes
330,D'Angelo Russell,Ohio St.,35,84.3,113.6,29.9,54.1,57.29,0.756,0.479,...,33.9429,1.0000,4.6571,5.0000,1.5714,0.3143,19.2857,Scoring PG,Yes,Yes
336,Jaylen Brown,California,34,68.3,95.4,30.9,47.1,51.76,0.654,0.482,...,27.6176,1.0588,4.2941,1.9706,0.7941,0.6471,14.6471,Wing F,Yes,Yes
349,Brandon Ingram,Duke,36,85.9,112.1,24.6,52.5,55.25,0.682,0.464,...,34.6111,1.8611,4.9167,1.9722,1.1111,1.3611,17.3333,Stretch 4,Yes,Yes
368,Ben Simmons,LSU,33,86.5,112.9,28.2,56.1,59.95,0.670,0.561,...,34.8788,3.1212,8.6364,4.7879,1.9697,0.8182,19.1515,Wing F,Yes,Yes
405,Jayson Tatum,Duke,29,65.3,108.9,25.4,50.7,56.61,0.849,0.504,...,33.3103,1.3448,6.0000,2.1379,1.3448,1.1379,16.8276,Wing F,Yes,Yes
464,Trae Young,Oklahoma,32,87.5,112.1,38.4,51.9,58.62,0.861,0.493,...,35.4062,0.4375,3.4688,8.6562,1.6875,0.2500,27.3750,Pure PG,Yes,Yes
484,Devin Booker,Kentucky,38,51.9,121.0,20.5,57.1,60.02,0.828,0.527,...,21.5000,0.4474,1.5526,1.1053,0.4474,0.0526,10.0263,Wing G,Yes,Yes
501,Zion Williamson,Duke,33,64.9,129.2,28.2,70.8,70.19,0.640,0.747,...,29.9697,3.5152,5.3636,2.0606,2.1212,1.7879,22.6061,Wing F,Yes,Yes

In [16]:
#alldrafted college picks
drafted_df['pick'].value_counts()

46.0    12
21.0    12
40.0    12
51.0    12
1.0     12
2.0     11
30.0    11
38.0    11
9.0     11
22.0    11
14.0    11
12.0    11
42.0    11
18.0    11
29.0    11
11.0    11
28.0    11
56.0    11
33.0    11
8.0     11
34.0    10
13.0    10
10.0    10
26.0    10
41.0    10
6.0     10
49.0    10
25.0    10
37.0    10
32.0    10
19.0     9
17.0     9
36.0     9
3.0      9
5.0      9
4.0      9
45.0     9
44.0     9
50.0     9
47.0     9
52.0     9
27.0     9
48.0     9
58.0     9
24.0     9
55.0     9
16.0     8
59.0     8
35.0     8
20.0     8
23.0     8
53.0     8
15.0     8
7.0      8
54.0     8
43.0     7
39.0     7
31.0     6
60.0     6
57.0     5
Name: pick, dtype: int64

In [17]:
# converting pick column to integer
drafted_df[['pick']].astype(int)

     pick
0      44
1      52
2      57
3      33
4      21
..    ...
567    29
568    22
569    43
570    21
571    51

[572 rows x 1 columns]

In [20]:
#saving to csv file
drafted_df.to_csv('drafted_vs_allstar.csv')